In [1]:
import pandas as pd

In [3]:
df = pd.read_table('./dataset/SMSSpamCollection')
df.columns = ['category', 'text']

In [4]:
df.describe()

       category                    text
count      5571                    5571
unique        2                    5168
top         ham  Sorry, I'll call later
freq       4824                      30

In [5]:
df['category'].describe()

count     5571
unique       2
top        ham
freq      4824
Name: category, dtype: object

In [6]:
df.sample(30)

     category                                               text
2649      ham  You might want to pull out more just in case a...
4225      ham  The world suffers a lot... Not because of the ...
3778      ham  Once a fishrman woke early in d mrng. It was v...
394       ham  Pick you up bout 7.30ish? What time are  and t...
2975      ham      Don't worry, * is easy once have ingredients!
2015      ham  Just re read it and I have no shame but tell m...
1274      ham  Let me know how to contact you. I've you settl...
2849     spam  YOUR CHANCE TO BE ON A REALITY FANTASY SHOW ca...
2690     spam  sports fans - get the latest sports news str* ...
1845      ham  Hi. || Do u want | to join me with sts later? ...
4022      ham  U gd lor go shopping i got stuff to do. U wan ...
298       ham  I cant pick the phone right now. Pls send a me...
3671      ham                      Yup. Thk of u oso boring wat.
2455      ham  Abeg, make profit. But its a start. Are you us...
1557      ham                                     Wat r u doing?
4771      ham                           Hi..i got the money da:)
5415      ham  My slave! I want you to take 2 or 3 pictures o...
3467     spam  URGENT! We are trying to contact U. Todays dra...
2911      ham                   Sorry,in meeting I'll call later
3651      ham       Want to send me a virtual hug?... I need one
2145     spam  Sunshine Hols. To claim ur med holiday send a ...
1626      ham                          Dear how you. Are you ok?
1540      ham               K come to nordstrom when you're done
4472     spam    3. You have received your mobile content. Enjoy
2980      ham  What u mean u almost done? Done wif sleeping? ...
3469      ham  All day working day:)except saturday and sunday..
2035      ham      Simply sitting and watching match in office..
1471      ham  Oh. U must have taken your REAL Valentine out ...
2581      ham  Yup i'm elaborating on the safety aspects and ...
3576      ham  The sign of maturity is not when we start sayi...

In [7]:
train_df = df.loc[:4449]

In [8]:
test_df = df.loc[4500:]

In [16]:
train_df.to_csv('./dataset/smsspam_train.tsv', sep='\t', header=0, index=False)

In [17]:
test_df.to_csv('./dataset/smsspam_test.tsv', sep='\t', header=0, index=False)